### ISSUE TITLE
ModuleNotFoundError: No module named 'utils'

### ISSUE THREAD

**Issue by mufeili** [ninglab/CTKG#1]
Running `loading_ctkg_in_dgl.ipynb` throws the error. You can fix the issue by removing the lines below

```python
import sys
sys.path.insert(1, 'utils')
from utils import download_and_extract
```

**Comment by BoPeng112** [comment]
Thanks for the comments! We fixed the error by changing the path of utils from "utils" to "../utils".

**Comment by mufeili** [comment]
Thanks for the update.
